### ISSUE TITLE
Add environment file for deployment mode

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/carp_studies_app#125]
Add environment files for the deployment mode to make sure that the testflight / production and so forth always have the same deployment mode

**Comment by LarsRefsgaard** [comment]
This will be even more important when the production gets deployed soon.
To hand this issue off, the idea is that you have an environment variable `STUDIES_DEPLOYMENT_MODE` that essentially replaces the `DeploymentMode` enum in the BLoC.
Then locally it is set to `local` or `dev` or whatever.
Then in the different Workflows in AppStoreConnect (Apple CI/CD pipeline system) you set the same environment variable to be `test`, `stage` or `production` depending on the workflow like shown here:
And do the same thing in GitHub Actions scripts or environment variables or fastlane or wherever it makes best sense to do this.
![image](https://github.com/cph-cachet/carp-studies-app/assets/1552887/95017548-87a0-4561-931b-93a5c3237d5c)

**Comment by LarsRefsgaard** [comment]
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by bardram** [comment]
For flutter - see

* https://stackoverflow.com/questions/44250184/setting-environment-variables-in-flutter

**Comment by bardram** [comment]
This has now been implemented. Copy of code documentation:

The BLoC is configured using two environment variables:
 * `deployment-mode` set the [DeploymentMode].
 * `debug-level` set the [DebugLevel].

In Flutter these environment variables is set by specifying the `--dart-define` option in `flutter run`. For example:

  `flutter run --dart-define=deployment-mode=local,debug-level=info`

In VSCode you need to add a `launch.json` file which looks like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "carp-studies-app (local mode)",
            "request": "launch",
            "type": "dart",
            "toolArgs": [
                "--dart-define",
                "deployment-mode=local",
                "--dart-define",
                "debug-level=debug"
            ]
        },
        {
            "name": "carp-studies-app (dev mode)",
            "request": "launch",
            "type": "dart",
            "toolArgs": [
                "--dart-define",
                "deployment-mode=dev",
                "--dart-define",
                "debug-level=debug"
            ],
            "flutterMode": "profile"
        },
        {
            "name": "carp-studies-app (production mode)",
            "request": "launch",
            "type": "dart",
            "toolArgs": [
                "--dart-define",
                "deployment-mode=production",
                "--dart-define",
                "debug-level=info"
            ],
            "flutterMode": "release"
        }
    ]
}
```
