### ISSUE TITLE
Update to typed go route

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/carp_studies_app#139]
Want to go over to typed routes so we can do `LoadingRoute().go(context);` instead of relying on strings like in `context.go('loading');`.
But right now shell routes which allow, for example, the `BottomNavigationBar` to stay on top of the UI in a nice manner is not supported in the `build_runner` that creates the routes from the typed routes...
This issue https://github.com/flutter/flutter/issues/111909 from the flutter repo tracks this. Most of the routes has been implemented in LarsRefsgaard/issue139

**Comment by LarsRefsgaard** [comment]
@Panosfunk This is a rather complicated feature I think and will require code changes in many places. There are files in the above mentioned branch that will guide you, but you probably need to start over from a fresh branch, as merging main at this point will probably be quite a hassle (you can try though). 

The documentation is very *concise*, meaning it not very thorough but also not very complicated in theory, however, in practice it can be quite difficult to work with.

https://pub.dev/packages/go_router
https://pub.dev/documentation/go_router/latest/topics/Type-safe%20routes-topic.html

**Comment by LarsRefsgaard** [comment]
Note that the assignee will have to use the [Build_runner](https://dart.dev/tools/build_runner) to generate files. @bardram knows how that works.

**Comment by bardram** [comment]
We added static strings for page names. This will do for now.
