### ISSUE TITLE
Data upload to CAWS fails if no login

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp_studies_app#213]
If the app is started and the user is already authenticated in a previous session, the login credential is not stored and cannot be accessed. And we get an error uploading data to CAWS:

````
[log] [CAMS INFO] CarpDataManager - Starting upload of data batches...
[log] [CAMS WARNING] CarpDataManager - Data upload failed - CarpServiceException: 401 Unauthorized -  null - null
```

It seems like the user object is `null`.

**Comment by bardram** [comment]
It seems like the access token has a very short expire data. This is an example of an access token downloaded at 10:57 - and it expires at 11:00, just **3 minutes**  later....

````
{
    "username": "jakob@bardram.net",
    "id": "f29f1b23-9d8f-4730-8e36-4dde519537a7",
    "email": "jakob@bardram.net",
    "first_name": "Jakob",
    "last_name": "Bardram",
    "roles": [
        "offline_access",
        "default-roles-carp",
        "uma_authorization",
        "participant"
    ],
    "token": {
        "access_token": "eyJh ... fGz7eg",
        "refresh_token": "eyJh ... dfMk",
        "token_type": "Bearer",
        "id_token": "eyJhbGciOiJ ... QJ_T80A",
        "scope": [
            "openid",
            "email",
            "profile"
        ],
        "expires_at": "2024-01-22T11:00:26.952"
    }
}
```
And since we upload data to CAWS every ** 10 minutes** this is bound to fail. 

2 Questions to @xelahalo :

* why is the token so short-lived?
* if the app tries to refresh the access token using the refresh token - will this work? Does the refresh token also expire after 3 minutes?

**Comment by bardram** [comment]
When reading here https://curity.io/resources/learn/oauth-refresh/#refresh-token-expiration it says that *"The lifetime of refresh tokens is configured in the identity server for each client application."*

@xelahalo - what is the case i CAWS?

**Comment by bardram** [comment]
I tried to refresh an expired token and it seems to work. The access token expired at `11:29` and was refreshed at `11:43` and got a new token that expired at `11:47`. 

So - it seems like I can use the refresh token even aften the access token has expired. BUT - for how long, I wonder?

**Comment by LarsRefsgaard** [comment]
all the attributes of a token is configurable in keycloak, so we can set both the refresh token and the normal token expiration time I believe.

**Comment by bardram** [comment]
I had a token that expired at `15:55` and at `17:22` I tried to refresh using the refresh token, and got

`CarpBackend - Failed to refresh access token - PlatformException(token_failed, Failed to get token: [error: invalid_grant, description: Session not active], null, null)`

So - it seems like the refresh token expires within an hour or so, which is WAY TOO SOON @xelahalo  ... We run studies that last for months......

**Comment by xelahalo** [comment]
What endpoint did you try to use to refresh the token? Can you give me a network dump to work with? @bardram

**Comment by xelahalo** [comment]
> When reading here https://curity.io/resources/learn/oauth-refresh/#refresh-token-expiration it says that *"The lifetime of refresh tokens is configured in the identity server for each client application."*
> 
> 
> 
> @xelahalo - what is the case i CAWS for the Studies App client?
> 
> 

I think it is the default value provided by Keycloak. But we might have changed that with @LarsRefsgaard, I don't remember, I will check it the next time I'm at the office.

This is a very insightful answer from SO regarding this topic:
https://stackoverflow.com/a/67624190

**Comment by bardram** [comment]
> What endpoint did you try to use to refresh the token? 

The URI for CAWS we're using is `https://carp.computerome.dk/dev` - I don't know the details of the refresh endpoint, though - this is part of the new implementation done by @LarsRefsgaard 

> Can you give me a network dump to work with? 

No. I only have the response from the server, which is

`PlatformException(token_failed, Failed to get token: [error: invalid_grant, description: Token is not active], null, null)`

**Comment by LarsRefsgaard** [comment]
It's using a library [AppAuth](https://appauth.io/) and [Flutter AppAuth](https://pub.dev/packages/flutter_appauth) to handle the exact network requests so I don't know either...
