### ISSUE TITLE
Back Button UI color needs changing

### ISSUE THREAD

**Issue by Goubeast** [cph-cachet/carp_studies_app#230]
I've included below the 'Learn More' page in Informed Consent or Survey Instructions. The ''Back Button" here should be the color of the text and not the page. The same is observed in light mode where this button is white and can't be seen clearly. 

![carp_app_bug](https://github.com/cph-cachet/carp_studies_app/assets/59992424/297ecae0-d40e-4a21-b1e0-1e930c14a5dd)

**Comment by SlimShadyIAm** [comment]
This is an issue in the Research Package and will be tracked here: https://github.com/cph-cachet/research.package/issues/101
