### ISSUE TITLE
Overflow error in Informed Consent due to lengthy text

### ISSUE THREAD

**Issue by Goubeast** [cph-cachet/carp_studies_app#231]
Given below is the Informed Consent Page 
![WhatsApp Image 2024-02-20 at 15 25 13 (1)](https://github.com/cph-cachet/carp_studies_app/assets/59992424/34712504-8e37-425c-b6d4-5352ea5be3d0)

If there is more text than that can fit on the page, we get an overflow error rather than a scroll bar to see all the text as shown below.
![WhatsApp Image 2024-02-20 at 15 25 13](https://github.com/cph-cachet/carp_studies_app/assets/59992424/b7fe622c-ce3b-43b7-80da-445ef7aac431)

This however does not happen in the 'Summary' Page of the informed consent where we can scroll and see all the text provided.

**Comment by SlimShadyIAm** [comment]
This is an issue in the Research Package and will be tracked here: https://github.com/cph-cachet/research.package/issues/100
