### ISSUE TITLE
When you log out stays in the same page

### ISSUE THREAD

**Issue by urganerea** [cph-cachet/carp_studies_app#232]
You need to exit the app in order to enter with another username.
Happens the same when you want to leave the study 
![IMG_2420](https://github.com/cph-cachet/carp_studies_app/assets/104897317/a8ab48c1-7cb3-4a86-a1cc-6c53a838ff18)

and just deletes the username and name parts:
![IMG_2417](https://github.com/cph-cachet/carp_studies_app/assets/104897317/2cc852b1-ffbb-4cda-8146-d515529f0cee)

**Comment by Panosfunk** [comment]
The dialog that is asking user to log out opens twice. First dialog does not do anything even if user presses yes. The 2nd dialog does actually log the user out but does not redirect to the InvitationsListPage as it should.

**Comment by Panosfunk** [comment]
When context.go(InvitationsPageList.route) is called this error occurs.

Exception has occurred.
FlutterError (This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.)
