### ISSUE TITLE
Leave the study warning message

### ISSUE THREAD

**Issue by urganerea** [cph-cachet/carp_studies_app#233]
"You are about to leave the study. You will no longer participate in this study. Are you sure?" 
I think it should be changed to something like: all the data collected will be deleted. Because you are able to participate in the study even if you leave, just data gets erased.

![IMG_2420](https://github.com/cph-cachet/carp_studies_app/assets/104897317/c998df9f-cdbd-435e-a1e9-6a12cb718ee7)

**Comment by bardram** [comment]
No data is deleted.
