### ISSUE TITLE
App throwing exception when trying to log in.

### ISSUE THREAD

**Issue by Panosfunk** [cph-cachet/carp_studies_app#239]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cachet.carp_studies_app/net.openid.appauth.RedirectUriReceiverActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by Panosfunk** [comment]
https://github.com/openid/AppAuth-Android/issues/1023

This seems to be fixing the issue but then when loading the invitations page activity, the app crashes

**Comment by SlimShadyIAm** [comment]
Can this be closed @Panosfunk?
