### ISSUE TITLE
Login page - username and password not accepted when autofilled

### ISSUE THREAD

**Issue by SlimShadyIAm** [cph-cachet/carp_studies_app#246]
When autofilling from a password manager (i.e Bitwarden) in the in-app browser on the Keycloak page, it does not accept it. But typing it manually seems to work.

Killing the app and restarting it seemed to resolve the issue?

This could be platform specific (iOS) -- more investigation needed.

**Comment by LarsRefsgaard** [comment]
i've definitely had that working with 1P
