### ISSUE TITLE
When you click on learn more in the app you can't go back, stuck on screen

### ISSUE THREAD

**Issue by cammdu** [cph-cachet/carp_studies_app#252]
there is no exit or back button, you can't leave screen. I encountered this problem when trying euroqol survey

**Comment by cammdu** [comment]
This was on my own phone (iphone xr), OS 16.5.1 when running the app normally (computerome server). There is an invisible button in the top left corner i think

**Comment by SlimShadyIAm** [comment]
Are you referring to the informed consent "learn more" page?

**Comment by cammdu** [comment]
hii, yes, anywhere where there are multiple slides to go through. for me it happened during a task from the tasks page.

**Comment by SlimShadyIAm** [comment]
this should already be fixed through #256, but if you find this issue again please open a new issue and include the steps to reproduce + screenshots
