### ISSUE TITLE
The tasks all disappear when app is closed

### ISSUE THREAD

**Issue by cammdu** [cph-cachet/carp_studies_app#253]
When you close the app and re-open again, all of the pending tasks disappear.

**Comment by bardram** [comment]
> When you close the app and re-open again, all of the pending tasks disappear.

@cammdu - you need to add much more info to this issue (and others). What do you mean by "close"? What device? What OS? What is the log print? Any warnings? Exceptions? etc.

**Comment by cammdu** [comment]
by close i meant no longer running in background, like completely closed. This was on my own phone (iphone xr), OS 16.5.1 when running the app normally (computerome server)

**Comment by bardram** [comment]
@SlimShadyIAm  and I have been working on upgrading the app to also address this. 

Please re-check now with the latest version @cammdu
