### ISSUE TITLE
Health Connect permissions for Google PLAY Store

### ISSUE THREAD

**Issue by Panosfunk** [cph-cachet/carp_studies_app#270]
Please fill in the following details.

## Device Hardware / Emulator and OS

Please complete the following information for each phone and/or emulator you're experiencing this bug on:

## Describe the bug

With the introduction of Health Connect API, Google complains when we try to deploy the app to their store saying that we need to have a reason to publish an app that asks for this type of data from the user because its intrusive to their personal data. 
We need to fill out [this](https://docs.google.com/forms/d/1LFjbq1MOCZySpP5eIVkoyzXTanpcGTYQH26lKcrQUJo/viewform?edit_requested=true&pli=1) form to ask for approval.

We need to provide:

- Application Name
- ApplicationID
- contract email address
- written reason as to why the app NEEDS to use Health Connect
- use cases of Health Connect in the app

This means that we either wait to get an official DTU Google account, or that we have to do the same process for both accounts.

## Stack trace and debug console

Include stack traces and debug print-outs below:

<details>
  <summary>Debug Output</summary>
  
  ```
    fastlane finished with errors

[!] Google Api Error: Invalid request - You need approval to use the following Health Connect permissions in your app: android.permission.health.READ_STEPS,android.permission.health.WRITE_STEPS,android.permission.health.READ_WEIGHT,android.permission.health.WRITE_WEIGHT,android.permission.health.READ_HEIGHT,android.permission.health.WRITE_HEIGHT,android.permission.health.READ_HEART_RATE,android.permission.health.WRITE_HEART_RATE,android.permission.health.READ_EXERCISE,android.permission.health.WRITE_EXERCISE,android.permission.health.READ_SLEEP,android.permission.health.WRITE_SLEEP,android.permission.health.READ_SPEED,android.permission.health.WRITE_SPEED,android.permission.health.READ_DISTANCE,android.permission.health.WRITE_DISTANCE,android.permission.health.READ_TOTAL_CALORIES_BURNED,android.permission.health.WRITE_TOTAL_CALORIES_BURNED,android.permission.health.READ_ACTIVE_CALORIES_BURNED,android.permission.health.WRITE_ACTIVE_CALORIES_BURNED,android.permission.health.READ_BLOOD_GLUCOSE,android.permission.health.WRITE_BLOOD_GLUCOSE,android.permission.health.READ_BLOOD_PRESSURE,android.permission.health.WRITE_BLOOD_PRESSURE,android.permission.health.READ_BODY_FAT,android.permission.health.WRITE_BODY_FAT,android.permission.health.READ_BODY_TEMPERATURE,android.permission.health.WRITE_BODY_TEMPERATURE,android.permission.health.READ_OXYGEN_SATURATION,android.permission.health.WRITE_OXYGEN_SATURATION,android.permission.health.READ_HYDRATION,android.permission.health.WRITE_HYDRATION,android.permission.health.READ_RESTING_HEART_RATE,android.permission.health.WRITE_RESTING_HEART_RATE,android.permission.health.WRITE_FLOORS_CLIMBED,android.permission.health.READ_FLOORS_CLIMBED,android.permission.health.WRITE_BASAL_METABOLIC_RATE,android.permission.health.READ_BASAL_METABOLIC_RATE,android.permission.health.READ_RESPIRATORY_RATE,android.permission.health.WRITE_RESPIRATORY_RATE,android.permission.health.WRITE_NUTRITION,android.permission.health.READ_NUTRITION. Learn more: https://support.google.com/googleplay/android-developer/answer/12991134
  ```

</details>

**Comment by bardram** [comment]
I've now filled i the two forms.

**Comment by bardram** [comment]
New video on the topic

https://www.youtube.com/watch?v=Q1NmhIwlyl4&themeRefresh=1

**Comment by Panosfunk** [comment]
We have provided an account already, the issue was they did not have a study to participate in. See trello card for complying to Google play rules

**Comment by bardram** [comment]
> See trello card for complying to Google play rules

@Panosfunk - Note we are not using Trello anymore - this has to be transferred here.
