### ISSUE TITLE
Polar device seems connected but doesn't work on reconnect

### ISSUE THREAD

**Issue by Panosfunk** [cph-cachet/carp_studies_app#309]
Haven't yet looked into whether this is an app or a research.package issue but when I connect the polar device to the phone, if I turn the device off and on again, it appears in state 'Connecting' and then 'Connected' but the polar.hr monitor does not work on the data page.

If i press disconnect and then connect again through the app, everything works fine.

**Comment by bardram** [comment]
I think this was solved in the latest release of CAMS.
