### ISSUE TITLE
Make a good protocol for the stores to review our app with

### ISSUE THREAD

**Issue by Panosfunk** [cph-cachet/carp_studies_app#331]
Use/review the one we sent to Google Play which seemed to work fine.
- [ ] Add instruction step in the new protocol that includes image, audio and video support for them to test. (this does not exist in the current protocol that google has)

**Comment by bardram** [comment]
I'm not sure we need this - we really don't have any study-specific video or image, and we don't want to show arbitrary cat videos.....
